ALTER TABLE identities ALTER COLUMN full_name DROP NOT NULL;
ALTER TABLE identities ALTER COLUMN phone DROP NOT NULL;
ALTER TABLE identities ALTER COLUMN nationality DROP NOT NULL;
ALTER TABLE identities ALTER COLUMN country DROP NOT NULL;
